/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/SignIn`; params?: Router.UnknownInputParams; } | { pathname: `/auth/SignIn/styles`; params?: Router.UnknownInputParams; } | { pathname: `/auth/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `/auth/SignUp/styles`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Splash`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Splash/styles`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/Home`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/Home/styles`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/Profile/styles`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/SignIn`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/SignIn/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/SignUp`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/SignUp/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/Splash`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/Splash/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/Home/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/Profile/styles`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/SignIn${`?${string}` | `#${string}` | ''}` | `/auth/SignIn/styles${`?${string}` | `#${string}` | ''}` | `/auth/SignUp${`?${string}` | `#${string}` | ''}` | `/auth/SignUp/styles${`?${string}` | `#${string}` | ''}` | `/auth/Splash${`?${string}` | `#${string}` | ''}` | `/auth/Splash/styles${`?${string}` | `#${string}` | ''}` | `/tabs/Home${`?${string}` | `#${string}` | ''}` | `/tabs/Home/styles${`?${string}` | `#${string}` | ''}` | `/tabs/Profile${`?${string}` | `#${string}` | ''}` | `/tabs/Profile/styles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/SignIn`; params?: Router.UnknownInputParams; } | { pathname: `/auth/SignIn/styles`; params?: Router.UnknownInputParams; } | { pathname: `/auth/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `/auth/SignUp/styles`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Splash`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Splash/styles`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/Home`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/Home/styles`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/Profile/styles`; params?: Router.UnknownInputParams; };
    }
  }
}
